### ISSUE TITLE
urin incomplete and wrong

### ISSUE THREAD

**Issue by daalft** [unimorph/swe#3]
The entries for urin are

urin	urinens	N;DEF;NOM;SG
urin	urins	N;INDF;NOM;SG

However, it should have four forms, 

 . | INDEF | DEF
-----|-------|--------
NOM | urin | urinen
GEN | urins | urinens

As can be seen, the annotations are wrong, the two forms present are genitive.

**Comment by aryamccarthy** [comment]
Ack, that's not good! Do you mind submitting a pull request with the correct information?

**Comment by kbatsuren** [comment]
Hi all, I am closing this issue because the new update doesn't have this issue anymore. Please feel free to reopen it if you find similar mistakes.
